[Config Ieee802154]
network = simulations.smart_home_v1.SmartHomeV1Network
abstract = true

**.arp.typename = "GlobalArp"
**.netmaskRoutes = ""
*.radioMedium.backgroundNoise.power = -110dBm
*.configurator.config = xmldoc("startopology.xml")
*.configurator.addStaticRoutes = false

# app configuration

# Number of applications per sensor
*.sensor1.numApps = 1
*.sensor2.numApps = 1
*.sensor3.numApps = 1
*.sensor4.numApps = 2
*.sensor5.numApps = 1

# --------------------------------------------------
# App 0: Periodic monitoring traffic
# --------------------------------------------------
*.sensor*.app[0].typename = "UdpBasicApp"
*.sensor*.app[0].destAddresses = "monitoringServer"
*.sensor*.app[0].destPort = 1000
*.sensor*.app[0].sendInterval = 10s
*.sensor*.app[0].startTime = uniform(0s,10s)
*.sensor*.app[0].messageLength = 50B
*.sensor*.app[0].packetName = "PeriodicMonitoring"

# --------------------------------------------------
# App 1 on sensor4: Critical smoke alarm
# --------------------------------------------------
*.sensor4.app[1].typename = "UdpBasicApp"
*.sensor4.app[1].destAddresses = "monitoringServer"
*.sensor4.app[1].destPort = 2000
*.sensor4.app[1].startTime = 50s
*.sensor4.app[1].stopTime = 51s
*.sensor4.app[1].sendInterval = 1000s
*.sensor4.app[1].messageLength = 20B
*.sensor4.app[1].packetName = "CriticalSmokeAlarm"

# --------------------------------------------------
# Controller receives both traffic classes
# --------------------------------------------------
# Gateway only forwards packets
*.controller.numApps = 0

# Core monitoring server receives both traffic classes
*.monitoringServer.numApps = 2

*.monitoringServer.app[0].typename = "UdpSink"
*.monitoringServer.app[0].localPort = 1000

*.monitoringServer.app[1].typename = "UdpSink"
*.monitoringServer.app[1].localPort = 2000

# Actuators configured later
*.lamp*.numApps = 0

# routing table visualization
*.visualizer.routingTableVisualizer[0].displayRoutingTables = false
*.visualizer.routingTableVisualizer[0].displayRoutesIndividually = false
*.visualizer.routingTableVisualizer[0].lineShift = 0
*.visualizer.routingTableVisualizer[0].displayLabels = false

# interface table visualization
*.visualizer.interfaceTableVisualizer[0].displayInterfaceTables = false

# data link visualization
*.visualizer.numDataLinkVisualizers = 2
*.visualizer.dataLinkVisualizer[*].displayLinks = true
*.visualizer.dataLinkVisualizer[0].nodeFilter = "sensor* or controller"
*.visualizer.dataLinkVisualizer[1].*Color = "blue"
*.visualizer.dataLinkVisualizer[1].nodeFilter = "lamp* or controller"

# statistic visualization
*.visualizer.numStatisticVisualizers = 2
*.visualizer.statisticVisualizer[*].zIndex = 1

*.visualizer.statisticVisualizer[0].displayStatistics = true
*.visualizer.statisticVisualizer[0].signalName = "packetSent"
*.visualizer.statisticVisualizer[0].statisticExpression = "count"
*.visualizer.statisticVisualizer[0].sourceFilter = "**.controller.udp OR **.sensor*.udp"
*.visualizer.statisticVisualizer[0].format = "sent: %v pks"

*.visualizer.statisticVisualizer[1].displayStatistics = true
*.visualizer.statisticVisualizer[1].signalName = "packetReceived"
*.visualizer.statisticVisualizer[1].statisticExpression = "count"
*.visualizer.statisticVisualizer[1].sourceFilter = "**.controller.udp OR **.lamp*.udp"
*.visualizer.statisticVisualizer[1].format = "rcvd: %v pks"

[Config Ieee802154Power]
extends = Ieee802154
sim-time-limit = 100s

**.energyStorage.residualEnergyCapacity.result-recording-modes = +last


