[Config Ieee802154]
network = simulations.experiment2_reporting_interval.ReportingIntervalNetwork
abstract = true

**.arp.typename = "GlobalArp"
**.netmaskRoutes = ""
*.radioMedium.backgroundNoise.power = -110dBm
*.configurator.config = xmldoc("startopology.xml")
*.configurator.addStaticRoutes = false

# app configuration

# ==========================================================
# Smart Home Sensor Applications
# ==========================================================

# Every sensor sends periodic monitoring traffic
*.sensor[*].numApps = 1

*.sensor[*].app[0].typename = "UdpBasicApp"
*.sensor[*].app[0].destAddresses = "monitoringServer"
*.sensor[*].app[0].destPort = 1000
*.sensor[*].app[0].sendInterval = 10s
*.sensor[*].app[0].startTime = uniform(0s,10s)
*.sensor[*].app[0].messageLength = 50B
*.sensor[*].app[0].packetName = "PeriodicMonitoring"


*.sensor[*].mobility.initFromDisplayString = false
*.sensor[*].mobility.initialX = uniform(1m, 19m)
*.sensor[*].mobility.initialY = uniform(1m, 19m)
*.sensor[*].mobility.initialZ = 0m

# --------------------------------------------------
# Controller receives both traffic classes
# --------------------------------------------------
# Gateway only forwards packets
*.controller.numApps = 0

# Core monitoring server receives both traffic classes
*.monitoringServer.numApps = 2

*.monitoringServer.app[0].typename = "UdpSink"
*.monitoringServer.app[0].localPort = 1000

*.monitoringServer.app[1].typename = "UdpSink"
*.monitoringServer.app[1].localPort = 2000

# Actuators configured later
*.lamp*.numApps = 0

# routing table visualization
*.visualizer.routingTableVisualizer[0].displayRoutingTables = false
*.visualizer.routingTableVisualizer[0].displayRoutesIndividually = false
*.visualizer.routingTableVisualizer[0].lineShift = 0
*.visualizer.routingTableVisualizer[0].displayLabels = false

# interface table visualization
*.visualizer.interfaceTableVisualizer[0].displayInterfaceTables = false

# data link visualization
*.visualizer.numDataLinkVisualizers = 2
*.visualizer.dataLinkVisualizer[*].displayLinks = true
*.visualizer.dataLinkVisualizer[0].nodeFilter = "sensor* or controller"
*.visualizer.dataLinkVisualizer[1].*Color = "blue"
*.visualizer.dataLinkVisualizer[1].nodeFilter = "lamp* or controller"

# statistic visualization
*.visualizer.numStatisticVisualizers = 2
*.visualizer.statisticVisualizer[*].zIndex = 1

*.visualizer.statisticVisualizer[0].displayStatistics = true
*.visualizer.statisticVisualizer[0].signalName = "packetSent"
*.visualizer.statisticVisualizer[0].statisticExpression = "count"
*.visualizer.statisticVisualizer[0].sourceFilter = "**.controller.udp OR **.sensor*.udp"
*.visualizer.statisticVisualizer[0].format = "sent: %v pks"

*.visualizer.statisticVisualizer[1].displayStatistics = true
*.visualizer.statisticVisualizer[1].signalName = "packetReceived"
*.visualizer.statisticVisualizer[1].statisticExpression = "count"
*.visualizer.statisticVisualizer[1].sourceFilter = "**.controller.udp OR **.lamp*.udp"
*.visualizer.statisticVisualizer[1].format = "rcvd: %v pks"

[Config Ieee802154Power]
extends = Ieee802154
sim-time-limit = 600s

# ==========================================================
# Experiment 2 - Result Recording
# ==========================================================

# Total packets generated by all active sensors
*.sensor[*].app[0].packetSent.result-recording-modes = count

# Total packets successfully received at the server
*.monitoringServer.app[0].packetReceived.result-recording-modes = count

# End-to-end delay statistics
*.monitoringServer.app[0].endToEndDelay.result-recording-modes = +stats

# Throughput at the monitoring server
*.monitoringServer.app[0].throughput.result-recording-modes = vector

**.energyStorage.residualEnergyCapacity.result-recording-modes = +last

# ==========================================================
# Experiment 2 - Reporting Interval
# Fixed: N = 12 sensors, Payload = 50 B
# Variable: T = 1, 5, 10, 30, 60 seconds
# ==========================================================

[Config Reporting_T1]
extends = Ieee802154Power
*.numSensors = 12
*.sensor[*].app[0].sendInterval = 1s
repeat = 5
seed-set = ${repetition}

[Config Reporting_T5]
extends = Ieee802154Power
*.numSensors = 12
*.sensor[*].app[0].sendInterval = 5s
repeat = 5
seed-set = ${repetition}

[Config Reporting_T10]
extends = Ieee802154Power
*.numSensors = 12
*.sensor[*].app[0].sendInterval = 10s
repeat = 5
seed-set = ${repetition}

[Config Reporting_T30]
extends = Ieee802154Power
*.numSensors = 12
*.sensor[*].app[0].sendInterval = 30s
repeat = 5
seed-set = ${repetition}

[Config Reporting_T60]
extends = Ieee802154Power
*.numSensors = 12
*.sensor[*].app[0].sendInterval = 60s
repeat = 5
seed-set = ${repetition}

